version: '3.7'

services:
  db:
    container_name: siniara-db
    image: mariadb
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    environment:
      - MARIADB_ROOT_PASSWORD=secure-af
      - MARIADB_USER=bot
      - MARIADB_PASSWORD=botpw
      - MARIADB_DATABASE=siniara

  bot:
    container_name: siniara-bot
    build: .
    command: python main.py
    restart: unless-stopped
    environment:
      - DB_HOST=db
    depends_on:
      - db

networks:
  default:
    driver: bridge

volumes:
  database:
