DROP TABLE IF EXISTS follow;
DROP TABLE IF EXISTS user_settings;
DROP TABLE IF EXISTS channel_settings;
DROP TABLE IF EXISTS guild_settings;
DROP TABLE IF EXISTS twitter_user;
DROP TABLE IF EXISTS guild;